version: '3'

services:   
  mysql-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - "5001:3306"
      
  web:
    build: .
    image: dev_proj_3:${IMAGE_TAG}
    ports:
      - "5000:5000"
    depends_on:
      - "mysql-db"
  